spring:
  application:
    name:elearner-ws
  h2:
    console:
      enabled: true
      setting:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:elearnerdb
    username: sa
    password: 123123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
      
